from typing import Protocol

from anonflow.bot.transport.types import RequestContext


class UserResponsesPort(Protocol):
    async def user_banned(self, context: RequestContext): ...
    async def user_not_registered(self, context: RequestContext): ...
    async def user_start(self, context: RequestContext): ...
    async def user_subscription_required(self, context: RequestContext): ...
    async def user_throttled(self, context: RequestContext, remaining_time: int): ...
